var nickNames = [
      'The Atomic Flea',
      'The Refridgerator',
      'Ironhead',
      'Flash',
      'Sweet Feet',
      'Shoeless',
      'The Enigma',
      'Tiny',
      'The GOAT',
      'Bacon Master',
      'The Big Unit',
      'Hot Donut',
      'Niblets',
      'Buffet Destroyer',
      'The Sexy Panda',
      'Real Deal',
      'Thunder From Down Under',
      'Grim Reaper',
      'The Yello Mamba',
      'Swaggy P',
      'Hard Ball',
      'Stinky',
      'White Chocolate',
      'Greased Lightning',
      'Snake Shot',
      'Boomstick',
      'Godzilla',
      'The Flying Nun',
      'Sweet Pea',
      'The Big Hurt',
      'Sweetness',
      'Killer Bee',
      'No Spins',
      'Ghost Rider',
      'Goose',
      'The Hitman',
      'The Iceman',
      'The Mailman',
      'The Mountain',
      'Just A Really OK Dude',
      'Prime Time',
      'The Intimidator',
      'Crazy Legs',
      'Danger',
      'The Dream',
      'The Microwave',
      'Bob',
      'Golden Toes',
      'Bowling Ball',
      'Bad Santa',
      'Chowderfoot',
      'Chunderbucket',
      'Twelve Toes',
      'The Dunwich Horror',
      'Party Fowl',
      'Pumpernickle',
      'Zuckerberg',
      'Genghis Can\'t',
      'Fancy Feast',
      'Shmoopie Poops',
      'Cuddle Flood',
      'Tater Cakes',
      'Fluffernutter',
      'The Question Mark',
      'Double Trouble',
      'Melon Belly',
      'Burger King',
      'Ponzi Scheme',
      'Ham Bone',
      'Pack O\' Smokes',
      'Muffin Man',
      'Nitro',
      'Blaser',
      'The Hammerhead'
    ];

var prefixes = [
      'Amazing ',
      'Automatic ',
      'Bombastic ',
      'Brawny ',
      'Curvy ',
      'Cinnamon Scented ',
      'Dominating ',
      'Domesticated ',
      'Eternal ',
      'Elite ',
      'Enthusiastic ',
      'Essential Oil of ',
      'Fearsome ',
      'Fumbling ',
      'Fightin\' ',
      'Formerly known as the ',
      'Galloping ',
      'Hairless ',
      'Invincible ',
      'Innocent Until Proven Guilty ',
      'Just the ',
      'Killer ',
      'Maniacal ',
      'Magical ',
      'Manchester ',
      'Mammoth ',
      'Maurading ',
      'Mighty ',
      'Mauled by ',
      'Nefarious ',
      'Not Nice ',
      'Oh No It\'s the ',
      'Perilous ',
      'Prickly',
      'Robotic ',
      'Rapcious ',
      'Stinky ',
      'Slap-Happy ',
      'Stupendous ',
      'Sweet ',
      'Terrible ',
      'United by ',
      'Made of ',
      'Smells like ',
      'Smarter than your average ',
      'Well Done ',
      'A Nice Side of ',
      'Dances with ',
      'Monkey Fightin\' ',
      'Drunk ',
      'Strongly Typed ',
      'A Lightweight Framework for ',
      'Rougishly Handsome ',
      'Save the ',
      'Rock Me ',
      'Hay is for ',
      'Flock of ',
      'A Barrel of ',
      'Basic ',
      'East Idaho ',
      'Deep Indigo Blue ',
      'The Harlem ',
      'They looked kind of like ',
      'Fresh Squeezed ',
      'Crab Fishin\' ',
      'Everybody Says They\'re the Best ',
      'Painfully Honest ',
      'The People Who Ate The '
    ];

var nouns = [
      'Advarks',
      'Authoritarian Dictators',
      'Actuaries',
      'Certified Public Accountants',
      'Cyber Security Experts',
      'Bears',
      'Boars',
      'Bobs',
      'Blobfish',
      'Baboons',
      'Baby Boomers',
      'Browns',
      'Bush Pigs',
      'Chipmunks',
      'Car Salesmen',
      'Ducks',
      'Dogs',
      'Donkeys',
      'Emus',
      'Eagles',
      'Executive Assistants',
      'Flip Flops',
      'Fishermen',
      'Guy Fieris',
      'Gorgons',
      'Grandmas',
      'Geese',
      'Ideas That Are Yours BUT GOD DAMN KAREN STOLE',
      'Impressionist Paintings',
      'Jorns',
      'Kangaroos',
      'Kittens',
      'Koalas',
      'Lemurs',
      'Llamas',
      'Laser Beams',
      'Long Lost Loves',
      'Loud Noises',
      'Lightning',
      'Ligonberries',
      'Meatballs',
      'Marketing Ideas',
      'Mastadons',
      'Mammoths',
      'Millenials',
      'Nerds',
      'Narwhals',
      'Ninjas',
      'Ostriches',
      'Pandas',
      'Polar Bears',
      'Pandolins',
      'Porcupines',
      'Potato Guns',
      'Pigeons',
      'Quails',
      'Racoons',
      'Rapping Grandmothers',
      'Sea Gulls',
      'Salespeople',
      'Silly Ninnies',
      'Tigers',
      'Toasters',
      'Terriers',
      'Tarantulas',
      'Thunder',
      'Trust Fund Kids',
      'Tweens',
      'Therapists',
      'Underdogs',
      'Uncles',
      'Uber Drivers',
      'Wizards',
      'Xenomorphs',
      'Zebras'
    ];

  function getNickname(){
    const nickIndex = Math.floor(Math.random() * nickNames.length);
    return nickNames[nickIndex];
  }

  function getTeamName(){
    const preIndex = Math.floor(Math.random() * prefixes.length);
    const nounIndex = Math.floor(Math.random() * nouns.length);
    return prefixes[preIndex] + nouns[nounIndex];
  }
